"""Add journalist model and journalist_id to articles

Revision ID: 48da13bd49db
Revises: 4be4749c386f
Create Date: 2026-07-28 11:31:29.271061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48da13bd49db'
down_revision: Union[str, Sequence[str], None] = '4be4749c386f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journalists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('media_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index(op.f('ix_journalists_id'), 'journalists', ['id'], unique=False)
    op.add_column('articles', sa.Column('journalist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'journalists', ['journalist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'journalist_id')
    op.drop_index(op.f('ix_journalists_id'), table_name='journalists')
    op.drop_table('journalists')
    # ### end Alembic commands ###
